# Generated by Django 4.1 on 2023-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="image", field=models.URLField(null=True),
        ),
    ]
