# Generated by Django 4.1 on 2023-11-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_image"),
        ("post", "0002_recommend_post_recommend_users_recommend_post_and_more"),
    ]

    operations = []
