# Generated by Django 4.1 on 2023-10-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='interest_users',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
