# Generated by Django 4.1 on 2023-11-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_merge_20231116_0751"),
        ("post", "0003_merge_20231116_0822"),
    ]

    operations = []
