# Generated by Django 4.1 on 2023-10-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaluser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personaluser',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
