# Generated by Django 4.1 on 2023-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_personaluser_email_alter_personaluser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaluser',
            name='grade',
            field=models.CharField(choices=[('17', '17학번 이상'), ('18', '18학번'), ('19', '19학번'), ('20', '20학번'), ('21', '21학번'), ('22', '22학번'), ('23', '23학번')], default='23', max_length=10),
        ),
        migrations.AddField(
            model_name='personaluser',
            name='interest',
            field=models.CharField(choices=[('music', '음악'), ('dance', '음악'), ('theater', '음악'), ('social', '사교'), ('sports', '운동'), ('religion', '종교'), ('art', '예술')], default='music', max_length=10),
        ),
        migrations.AddField(
            model_name='personaluser',
            name='major',
            field=models.CharField(choices=[('Business', '경영대학'), ('Engineering', '공과대학'), ('Art', '미술대학'), ('Education', '사범대학'), ('SocialSciences', '사회과학대학')], default='Business', max_length=20),
        ),
        migrations.AddField(
            model_name='personaluser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Group', 'Group')], default='User', max_length=10),
        ),
    ]
