# Generated by Django 4.1 on 2023-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_personaluser_grade_personaluser_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaluser',
            name='email',
            field=models.EmailField(default='s.lee.0713@snu.ac.kr', max_length=254),
        ),
    ]
