# Generated by Django 4.1 on 2023-11-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_personaluser_grade_alter_personaluser_interest_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(name="personaluser", managers=[],),
    ]
