# Generated by Django 4.1 on 2023-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_personaluser_grade_alter_personaluser_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaluser',
            name='major',
            field=models.CharField(choices=[('Business', '경영대학'), ('Engineering', '공과대학'), ('Art', '미술대학'), ('Education', '사범대학'), ('SocialSciences', '사회과학대학'), ('Music', '음악대학'), ('Humanities', '인문대학'), ('NaturalSciences', '자연과학대학')], default='Business', max_length=20),
        ),
    ]
