# Generated by Django 4.1 on 2023-10-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_personaluser_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
