# Generated by Django 4.1 on 2023-10-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_personaluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaluser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
