# Generated by Django 4.1 on 2023-10-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_personaluser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaluser",
            name="grade",
            field=models.CharField(
                choices=[
                    ("16", "16학번 이상"),
                    ("17", "17학번"),
                    ("18", "18학번"),
                    ("19", "19학번"),
                    ("20", "20학번"),
                    ("21", "21학번"),
                    ("22", "22학번"),
                    ("23", "23학번"),
                ],
                default="23",
                max_length=10,
            ),
        ),
    ]
