# Generated by Django 4.2.6 on 2023-10-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='duration',
            name='event_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='duration',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
